// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQADEa10R-vo4ko4DDBopghVFeo3qMGQc',
    appId: '1:164240324488:web:915af3a22523120b9dac3d',
    messagingSenderId: '164240324488',
    projectId: 'smartedge-iot-app',
    authDomain: 'smartedge-iot-app.firebaseapp.com',
    databaseURL: 'https://smartedge-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartedge-iot-app.appspot.com',
    measurementId: 'G-G3TQ90MT9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMYlfnmK92oIdOqsFbwJIio_kOoAMeWJA',
    appId: '1:164240324488:android:eabc0ae5d96224759dac3d',
    messagingSenderId: '164240324488',
    projectId: 'smartedge-iot-app',
    databaseURL: 'https://smartedge-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartedge-iot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNyp0UDvZ5C-C9fP0u2g5W5qumyACxD0',
    appId: '1:164240324488:ios:768771e02e8a11869dac3d',
    messagingSenderId: '164240324488',
    projectId: 'smartedge-iot-app',
    databaseURL: 'https://smartedge-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartedge-iot-app.appspot.com',
    iosBundleId: 'com.example.afnHydroLink',
  );
}
